### ISSUE TITLE
[!] Unable to find a specification for `CountryPickerView`

### ISSUE THREAD

**Issue by joprithiviraj** [kizitonwose/CountryPickerView#1]
I tried to install but have getting " [!] Unable to find a specification for `CountryPickerView`
" this error. Also added CountryPickerView.Framework but getting crash. Im using Xcode 8.3.2.

Thanks in advance.

**Comment by kizitonwose** [comment]
Which method are you using to install the library? CocoaPods or Carthage?

**Comment by joprithiviraj** [comment]
I used cocoaPods

**Comment by kizitonwose** [comment]
You're getting this error because `CountryPickerView` is new and your local podspec repository doesn't have the specification for it yet. You need to run: 

`pod install --repo-update` 

This updates your local podspec repository and installs the pods in your Podfile.

**Comment by joprithiviraj** [comment]
Its working fine.... thanking you @kizitonwose
