### ISSUE TITLE
App Crashing

### ISSUE THREAD

**Issue by arun-macrew** [kizitonwose/CountryPickerView#101]
App crashing on select country after search the country from the list.

Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Application tried to present modal view controller on itself. Presenting controller is <UISearchController: 0x10c815e00>.'
*** First throw call stack:
(0x194802a48 0x194529fa4 0x19826ba80 0x19826dc6c 0x19826e168 0x19826dbbc 0x19826de24 0x1988e0958 0x198286600 0x198282d4c 0x198282a90 0x19887f128 0x19886ec78 0x19889eac8 0x19477fe68 0x19477ad54 0x19477b320 0x19477aadc 0x19e700328 0x198875ae0 0x10441f52c 0x194604360)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by kizitonwose** [comment]
I cannot reproduce this issue, can you tell me what you did to get it to crash?

**Comment by arun-macrew** [comment]
@kizitonwose Search the country from country list after that select the searched country then app is crashing on selection of country

**Comment by bluesky375** [comment]
Here same as arun-macrew.

**Comment by ahsanghauri** [comment]
same issue

**Comment by arun-macrew** [comment]
@kizitonwose Are you able to solve this issue or we find another way to complete our work.

**Comment by kizitonwose** [comment]
@arun-macrew I can't fix what I can't reproduce. If you have a fix that works for you, open a PR.

**Comment by kizitonwose** [comment]
@ahsanghauri @bluesky375 Sharing your device model and OS version may be helpful.

**Comment by amrutWaghmare** [comment]
I'm getting the same issue.

**Comment by fahadmohaimin** [comment]
getting same issue

**Comment by fahadmohaimin** [comment]
Device Simulator iphone 11 pro max .. OS:Mojave 10.14.6.. app crashes after search and selection

**Comment by klawsachkar** [comment]
2020-01-28 13:52:26.719710+0200 *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Application tried to present modal view controller on itself. Presenting controller is <UISearchController: 0x7fe34315dc00>.'

[Screen Recording 2020-01-28 at 1.51.57 PM.mov.zip](https://github.com/kizitonwose/CountryPickerView/files/4122207/Screen.Recording.2020-01-28.at.1.51.57.PM.mov.zip)

**Comment by klawsachkar** [comment]
I got to avoid the issue by setting the searchBarPosition to navigationBar in the CountryPickerViewDelegate
`func searchBarPosition(in countryPickerView: CountryPickerView) -> SearchBarPosition {
        return .navigationBar
    }`

**Comment by kizitonwose** [comment]
> Device Simulator iphone 11 pro max .. OS:Mojave 10.14.6.. app crashes after search and selection

Tested on the sample project in the repo but it does not crash with this configuration.

**Comment by kizitonwose** [comment]
Can someone maybe test with [this change](https://github.com/kizitonwose/CountryPickerView/pull/95/files) and see if it fixes the issue as I can't reproduce this issue in the sample project.

**Comment by mathimca** [comment]
> Can someone maybe test with [this change](https://github.com/kizitonwose/CountryPickerView/pull/95/files) and see if it fixes the issue as I can't reproduce this issue in the sample project.

Yes ,it fixed the issue, thanks

**Comment by arun-macrew** [comment]
Yes ,it fixed the issue, thanks

**Comment by kizitonwose** [comment]
I'll publish a new version of the library with the fix later this evening.

**Comment by kizitonwose** [comment]
For anyone interested, this is now fixed in version [3.0.8](https://github.com/kizitonwose/CountryPickerView/releases/tag/3.0.8)
