### ISSUE TITLE
Issue with black status bar

### ISSUE THREAD

**Issue by sandeepbol** [kizitonwose/CountryPickerView#102]
I have a UI requirement to use a black background color for the status bar. For that, we need to use the status bar tint color as white. Is it possible to do that?

![File](https://user-images.githubusercontent.com/25767241/71713458-daf43700-2e2f-11ea-915c-d70b972e6e17.jpg)

**Comment by arun-macrew** [comment]
@sandeepbol Your app is also crashing while selecting country after search the country from the list ?

**Comment by sandeepbol** [comment]
nope @arun-macrew Everything is working fine except this styling.

**Comment by kizitonwose** [comment]
How are you setting the status bar color? How can the library help? I'm not sure I understand this issue, so kindly explain further.

**Comment by sandeepbol** [comment]
This is how status bar color is set:
`        UIApplication.shared.statusBarView?.backgroundColor = .black
`
Now time, network provider, etc. is invisible as it's in black color. Since after presenting the CountryPickerView, I do not have control over setting the tintColor, I am looking for help.

**Comment by kizitonwose** [comment]
Okay, so how are you setting the tint of the status bar items in other parts of the app?

**Comment by sandeepbol** [comment]
By overriding
```    
    public override var preferredStatusBarStyle: UIStatusBarStyle {
        return .lightContent
    }
```
and in the navigation bar:
```
    override var preferredStatusBarStyle: UIStatusBarStyle {
        return self.topViewController?.preferredStatusBarStyle ?? .default
    }
```

**Comment by kizitonwose** [comment]
Unfortunately, this is not supported. 
If you are pushing the picker on your own nav controller stack, in your `preferredStatusBarStyle` property, you can check the top view controller and return the desired value if it is the picker else proceed with the usual.
