### ISSUE TITLE
searchController is nil in willShow delegate method

### ISSUE THREAD

**Issue by eralnar** [kizitonwose/CountryPickerView#116]
Hey! Is there a way to customize the searchBar in the willShow before the view appears? 
As I said, searchController is still nil in willShow delegate method, so I can only change it in didShow method with the expected style change when user is already on the view.

**Comment by eralnar** [comment]
@kizitonwose would you help me?

**Comment by kizitonwose** [comment]
Hello @canedo2, very sorry for the late response. If you are still looking for a way to do this, you can force the view to be loaded in the `willShow` method:

```swift
func countryPickerView(_ countryPickerView: CountryPickerView, willShow viewController: CountryPickerViewController) {
    viewController.loadViewIfNeeded()
    viewController.searchController.searchBar // Searchbar is now available
}
```

**Comment by eralnar** [comment]
Thank you very much @kizitonwose. I would like to know how to center searchBar also, maybe you can help me with that. I would like to add a margin to both sides and leave it centered if it is possible. Is it viable? I also have the animation when cancel button is appearing.

![Captura de pantalla 2020-04-20 a las 16 29 06](https://user-images.githubusercontent.com/23417387/79763333-3b967980-8324-11ea-8ca4-577e2fdb881a.png)

I have to say everything works very well, thank you for your job.

**Comment by kizitonwose** [comment]
You can use `NSDirectionalEdgeInsets` in the `willShow` method. Something like this:

```swift
func countryPickerView(_ countryPickerView: CountryPickerView, willShow viewController: CountryPickerViewController) {
    viewController.loadViewIfNeeded()
    let directionalMargins = NSDirectionalEdgeInsets(top: 0, leading: 20, bottom: 0, trailing: 10)
    viewController.searchController?.searchBar.directionalLayoutMargins = directionalMargins
}
```

However, the above code requires iOS 11+, so if that's not the case for your project, then you can fall back to `UIEdgeInsets`:

```swift
func countryPickerView(_ countryPickerView: CountryPickerView, willShow viewController: CountryPickerViewController) {
    viewController.loadViewIfNeeded()
    let edgeInsets = UIEdgeInsets(top: 0, left: 20, bottom: 0, right: 10)
    viewController.searchController?.searchBar.layoutMargins = edgeInsets
}
```

These both give the same result. You can adjust the values as needed.

**Comment by eralnar** [comment]
Thank you so much for help, I'm closing the issue.

**Comment by eralnar** [comment]
Hey, I'm having problems to apply edgeInsets and cornerRadius at the same time in the willShow delegate:


```
viewController.loadViewIfNeeded() //Loads searchBar
        if let searchBar = viewController.searchController?.searchBar,
            let textFieldInsideUISearchBar = searchBar.value(forKey: "searchField") as? UITextField,
            let labelInsideUISearchBar = textFieldInsideUISearchBar.value(forKey: "placeholderLabel") as? UILabel {

            searchBar.tintColor = UIColor.elluBlack
            searchBar.backgroundImage = UIImage()
            searchBar.backgroundColor = UIColor.white
            let directionalMargins = NSDirectionalEdgeInsets(top: 0, leading: 16, bottom: 0, trailing: 16)
            searchBar.directionalLayoutMargins = directionalMargins
            textFieldInsideUISearchBar.textColor = UIColor.elluBlack
            textFieldInsideUISearchBar.font = UIFont.openSansRegular(17.0)
            textFieldInsideUISearchBar.borderStyle = .roundedRect
            textFieldInsideUISearchBar.layer.cornerRadius = textFieldInsideUISearchBar.frame.size.height / 2
            textFieldInsideUISearchBar.layer.masksToBounds = true
            textFieldInsideUISearchBar.backgroundColor = UIColor.elluVeryLightGray
            labelInsideUISearchBar.textColor = UIColor.elluMainGray

        }
```

It seems to work correctly on didShow, so I suppose I need to layout searchBar but layoutIfNeeded is not working, which order should it take?

**Comment by kizitonwose** [comment]
If I understand clearly, `cornerRadius` works in `willShow` without `edgeInsets` and vice versa?

**Comment by eralnar** [comment]
Yes, I can't apply both at the same time, but applying both separately works correctly, applying both u see in the code results on no change on UI

Edit: textFieldInsideUISearchBar.frame.size.height == 0 in willShow,  == 36 in didShow. If I apply 18 to corner radius it works propely in willShow.

Another note is, using NSDirectionalEdgeInsets I cant make trailing less than the default amount, I think it is related to Cancel button.

**Comment by kizitonwose** [comment]
Well, that's unfortunate. Nothing else comes to mind on how to further assist you with this. You may just download the library and include it in your project so you can make as much customizations as needed.

**Comment by eralnar** [comment]
Thank you very much for assisting me, that was quite enough 👍
