### ISSUE TITLE
Issue while set country phone code

### ISSUE THREAD

**Issue by kETANoPENXCELL** [kizitonwose/CountryPickerView#117]
Hello Team,

I am facing issues while setting country phone code.

Here is my code for more review.

private let countryPickerView = CountryPickerView()
UserModel.sharedUser.strPhone = "+91 9999999999"

let countryArray = UserModel.sharedUser.strPhone.components(separatedBy: " ")

                if(countryArray.count > 1) {
                    self.countryCode = countryArray[0]//+91
                    self.txtPhone.text = countryArray[1]//9999999999
                }
                else {
                    self.countryCode = "+65"
                    self.txtPhone.text = UserModel.sharedUser.strPhone//9999999999
                }
                
                self.countryPickerView.delegate = self
                self.countryPickerView.setCountryByPhoneCode(self.countryCode)

extension MYCONTROLLER: CountryPickerViewDelegate {
    
    func countryPickerView(_ countryPickerView: CountryPickerView, didSelectCountry country: Country) {
        countryCode = country.phoneCode
        ivCountryImage.image = country.flag
    }
    
}

But it is not reflecting on UI.

**Comment by kizitonwose** [comment]
It's not reflecting because the delegate is not called if you set the country by yourself. This is a bug which is now fixed in version [3.1.2](https://github.com/kizitonwose/CountryPickerView/releases/tag/3.1.2)
