### ISSUE TITLE
Type 'VerifyAccountVC' does not conform to protocol 'CountryPickerViewDelegate'

### ISSUE THREAD

**Issue by DhavalGevariya** [kizitonwose/CountryPickerView#119]
![Screenshot 2020-05-07 at 9 35 57 PM](https://user-images.githubusercontent.com/30233160/81317695-c90af500-90aa-11ea-83e5-3eadd82074e0.png)

Hello 

why this ?? i have already assign a delegate method and also use delegate method but why this error comes.

**Comment by kizitonwose** [comment]
There's a message in the README about this:

> Note: If you already have a Country class or struct in your project then implementing the didSelectCountry delegate method can cause a compile error with a message saying that your conforming class does not comform to the CountryPickerViewDelegate protocol. This is because Xcode can't figure out which Country model to use in the method. The solution is to replace the Country in the method signature with the typealias CPVCountry, your delegate method should now look like this:

```swift
func countryPickerView(_ countryPickerView: CountryPickerView, didSelectCountry country: CPVCountry)
```

**Comment by kizitonwose** [comment]
In summary:

Replace:

```swift
func countryPickerView(_ countryPickerView: CountryPickerView, didSelectCountry country: Country)
```

with: 

```swift
func countryPickerView(_ countryPickerView: CountryPickerView, didSelectCountry country: CPVCountry)
```

**Comment by DhavalGevariya** [comment]
Thanks It's Working.
