### ISSUE TITLE
Unable to load from my own Xib

### ISSUE THREAD

**Issue by markturnip** [kizitonwose/CountryPickerView#120]
I'd like to be able to load using my own xib.

Should usually be possible by passing in owner or instantiating using:
`Bundle.main.loadNibNamed("CountryPickerView", owner: nil, options: [:])`

**Comment by kizitonwose** [comment]
What error do you get when you do this?

**Comment by markturnip** [comment]
No error, it's simply due to `NibView` implicitly loading from bundle, rather than being able to define a view in storyboard/ib which subclasses `CountryPickerView`.

https://github.com/kizitonwose/CountryPickerView/blob/master/CountryPickerView/NibView.swift#L36

**Comment by kizitonwose** [comment]
To be honest, I don't think I fully understand this issue. Can you please explain further?

> I'd like to be able to load using my own xib.

By this do you mean like using the library in interface builder or what?

**Comment by kizitonwose** [comment]
Closing this, feel free to comment if you still need assistance.
