### ISSUE TITLE
CountryPickerViewDataSource doesn't have UIKit imported

### ISSUE THREAD

**Issue by NSCabezon** [kizitonwose/CountryPickerView#121]
Hi, while adding the dependency with SPM the class `CountryPickerViewDelegate` complains about the following:
<img width="1009" alt="Captura de pantalla 2020-05-20 a las 10 59 59" src="https://user-images.githubusercontent.com/563761/82427205-0dbe6500-9a89-11ea-81c0-8293ed094664.png">

**Comment by NSCabezon** [comment]
this fixed it, FYI

https://github.com/NSCabezon/CountryPickerView/commit/82d4f07ef82dff15282690d011cbd3e8707c0df9

**Comment by kizitonwose** [comment]
> this fixed it, FYI
> 
> [NSCabezon@82d4f07](https://github.com/NSCabezon/CountryPickerView/commit/82d4f07ef82dff15282690d011cbd3e8707c0df9)

Thanks, I will include this in the next release.

**Comment by kizitonwose** [comment]
Fixed in [3.1.3](https://github.com/kizitonwose/CountryPickerView/releases/tag/3.1.3)
