### ISSUE TITLE
How to exclude a particular country from list of all country

### ISSUE THREAD

**Issue by Pairroxz** [kizitonwose/CountryPickerView#122]
I try to find how to exclude some countries in CountryPickerView, Please suggest the correct way to achieve it. Thanks

**Comment by kizitonwose** [comment]
You could just set the preferred countries and remove the ones you don't want to show.

```swift
extension DemoViewController: CountryPickerViewDataSource {
    func preferredCountries(in countryPickerView: CountryPickerView) -> [Country] {
        return countryPickerView.countries.filter {
            // Filter the countries you want to show.
        }
    }
    
    func sectionTitleForPreferredCountries(in countryPickerView: CountryPickerView) -> String? {
        return "Preferred title"
    }
    
    func showOnlyPreferredSection(in countryPickerView: CountryPickerView) -> Bool {
        return true
    }
}
```

**Comment by Pairroxz** [comment]
@kizitonwose As you suggested to use` preferredCountries` function I already used that for showing user current country. See in image [https://www.dropbox.com/s/o3cl0rotwekzkux/Simulator%20Screen%20Shot%20-%20iPhone%2011%20Pro%20Max%20-%202020-06-24%20at%2010.04.56.png?dl=0](url) 

I would like to remove a country from rest of the list and from searching for example `Afghanistan` So how will this achieve.

One solution I have made in Pod folder I removed the json object of that country, remove related flag resource, and from `Copy and bundle resources` I removed the link of flag icon. That works for me but that is temporary solution. as I update the pod next time changes will undo. And need to do it again. 

Do you have any alternate way of doing this. Please suggest.

**Comment by kizitonwose** [comment]
Will add this feature in an upcoming version.

**Comment by kizitonwose** [comment]
Added in [3.1.3](https://github.com/kizitonwose/CountryPickerView/releases/tag/3.1.3)
