### ISSUE TITLE
Empty country list causes crash on Catalyst?

### ISSUE THREAD

**Issue by andygeers** [kizitonwose/CountryPickerView#124]
I have got this working nicely on iOS, but it seems to crash in my Catalyst version. The crash comes from:

```
internal(set) public var selectedCountry: Country {
        get {
            return _selectedCountry
                ?? countries.first(where: { $0.code == Locale.current.regionCode })
                ?? countries.first!
        }
        set {
            _selectedCountry = newValue
            delegate?.countryPickerView(self, didSelectCountry: newValue)
            setup()
        }
    }
```
- because `countries` is empty, `countries.first!` crashes.

Countries is empty because `guard let jsonPath = bundle.path(forResource: "CountryPickerView.bundle/Data/CountryCodes", ofType: "json")` returns nil in the `public let countries: [Country]` method.

Any ideas how to fix this?

**Comment by kizitonwose** [comment]
I guess I need to find a reliable way of loading the JSON. Maybe you can play around with the sample project and let me know what works.

**Comment by kizitonwose** [comment]
Try 3.3.0 and see if this is fixed. I'll reopen this if needed.
