### ISSUE TITLE
need to search for any character on the country name

### ISSUE THREAD

**Issue by mEldewaik** [kizitonwose/CountryPickerView#125]
i need to search for a name with any character on it not only the first character 
ex. when i search for egypt when i type **e** i get egypt in the list and when i type **g** i don't get it so i need to search with any characters in the name

**Comment by mEldewaik** [comment]
@kizitonwose need your help

**Comment by kizitonwose** [comment]
Please check that you are on the latest version as I do not experience this issue.

<img src="https://user-images.githubusercontent.com/15170090/88450549-1ac44f80-ce50-11ea-81cf-af45154a9ef5.png" alt="screenshot" width="300">
