### ISSUE TITLE
some countries are not present (Ivary coast), West Africa

### ISSUE THREAD

**Issue by shubham14896** [kizitonwose/CountryPickerView#126]

**Comment by kizitonwose** [comment]
Just checked and this is the case indeed. It will be added in an upcoming version. If you are able to submit a PR, that would speed things up as well.

**Comment by shubham14896** [comment]
Sure

**Comment by shubham14896** [comment]
@kizitonwose Check the PR - https://github.com/kizitonwose/CountryPickerView/pull/128

**Comment by kizitonwose** [comment]
Closing this as #128 is closed.
