### ISSUE TITLE
Modal picker doesn't display properly on iPhone X

### ISSUE THREAD

**Issue by ClaudeSutterlin** [kizitonwose/CountryPickerView#13]
When you tap in the search bar it bumps the search field off the screen. 

![simulator screen shot - iphone x - 2018-07-15 at 10 19 26](https://user-images.githubusercontent.com/423661/42734843-9446343e-8818-11e8-9dd6-aa6d5380df47.png)

**Comment by kizitonwose** [comment]
This issue was fixed in the last release([2.1.1](https://github.com/kizitonwose/CountryPickerView/releases/tag/2.1.1))
Are you on this version?

**Comment by ClaudeSutterlin** [comment]
I was using the latest from Cocoapods as of this morning. Thanks for fixing.

**Comment by bkucharskiDev** [comment]
Hey 👋 first of all thank you for this library! I'm using the latest version on iOS 12.1 and the problem still occurs. Can you fix it? :)
