### ISSUE TITLE
Not supporting in Xcode 12

### ISSUE THREAD

**Issue by devmuz** [kizitonwose/CountryPickerView#132]
All working good till Xcode version 11.x but when I start working on Xcode 12 and run the Pod Install, I am getting error 

`Debug-iphonesimulator/CountryPickerSwift-framework/CountryPicker.framework/Flags.car" not found. Run 'pod install' to update the copy resources script.`

However I tried this multiple times after remove/installing Pod library but same issue.

**Comment by kizitonwose** [comment]
Version 3.2.0 was released using Xcode 12 so I think this issue is not from the lib + Xcode 12 usage.
