### ISSUE TITLE
Get country name from country code Swift 5

### ISSUE THREAD

**Issue by NikicaAsanin** [kizitonwose/CountryPickerView#134]
Hi, is there option to **get country name from country code?** I need this example in my project because on app load I ask for user location and in return I get country code (ex. US) so I need somehow to user country code and to get country name in return, also this needs to happen on app load.

Thanks

**Comment by kizitonwose** [comment]
Why not create an instance of CountryPickerView and use that?

With an instance of the class, you can call `getCountryByCode()`
