### ISSUE TITLE
Make Country constructor public

### ISSUE THREAD

**Issue by marcioadr88** [kizitonwose/CountryPickerView#14]
I need to internationalize the Country name, but I can't create new Countries because the constructor is internal.

**Comment by kizitonwose** [comment]
How do you mean Internationalize? I don't follow, kindly explain further.

**Comment by kizitonwose** [comment]
Just saw your PR [here](https://github.com/kizitonwose/CountryPickerView/pull/15/files), is that what you mean?

**Comment by kizitonwose** [comment]
If that's the case, then you can easily wrap the Country struct in your own struct/class and provide this implementation. 

Something like this:
```swift
struct AppCountry {
    let country: Country
    var localizedName: String {
        return Locale.current.localizedString(forRegionCode: country.code) ?? country.name
    }
    
    init(country: Country) {
        self.country = country
    }
}
```
The Country struct only represents information that we bundle with the library(see [CountryCodes.json](https://github.com/kizitonwose/CountryPickerView/blob/master/CountryPickerView/Assets/CountryPickerView.bundle/Data/CountryCodes.json)), hence the internal constructor.
