### ISSUE TITLE
Is CountryPickerView no more?

### ISSUE THREAD

**Issue by kohlab** [kizitonwose/CountryPickerView#145]
I haven't seen any activity in this repository for a while. It's been quite useful, but it needs Swift Package Manager support to continue. Is it still active? If not, can it be handed off? Are there alternatives that people have moved to?

**Comment by kizitonwose** [comment]
SPM usage is now fixed in [3.3.0](https://github.com/kizitonwose/CountryPickerView/releases/tag/3.3.0) 🚀
