### ISSUE TITLE
Can't change color of UINavigationItems back button 

### ISSUE THREAD

**Issue by hamedaakhlaghi** [kizitonwose/CountryPickerView#16]
How can I change `leftBarButtonItem`'s color?

**Comment by kizitonwose** [comment]
There are new methods in `CountryPickerViewDelegate` in the latest version([2.1.1](https://github.com/kizitonwose/CountryPickerView/releases/tag/2.1.1)) that you can use to accomplish this.

`func countryPickerView(_ countryPickerView: CountryPickerView, willShow viewController: UITableViewController)`

**AND**

`func countryPickerView(_ countryPickerView: CountryPickerView, didShow viewController: UITableViewController)`

You can change the back button's color by calling 
`viewController.navigationController?.navigationBar.tintColor = desiredColor` from the first(willShow) delegate.

**Comment by hamedaakhlaghi** [comment]
I changed root navigation view controller's navigation bar view's tint color, it changed to that color.
