### ISSUE TITLE
Please help on reducing flag size and font size in Country list

### ISSUE THREAD

**Issue by sonnetm** [kizitonwose/CountryPickerView#19]

**Comment by SonicGerkor** [comment]
This would be great.
The image should have leading, top and bottom constraints, and we could change those values or just plainly change the size of the flagImageView.

Thanks!

**Comment by kizitonwose** [comment]
@sonnetm @SonicGerkor 
In the latest release ([2.2.0](https://github.com/kizitonwose/CountryPickerView/releases/tag/2.2.0)), you can use the `CountryPickerViewDataSource` methods:

- `func cellLabelFont(in countryPickerView: CountryPickerView) -> UIFont`
- `func cellImageViewSize(in countryPickerView: CountryPickerView) -> CGSize`

to configure the sizes of the label and images on the list.

**Comment by dosymbaev** [comment]
How to change image size in CountryPickerView not list?
