### ISSUE TITLE
Cant print phone number together with the selected country

### ISSUE THREAD

**Issue by egod-pablo007** [kizitonwose/CountryPickerView#22]
import UIKit
import CountryPickerView
class LoginController: UIViewController{

    @IBOutlet weak var phoneNumber: UITextField!
    override func viewDidLoad() {
        super.viewDidLoad()

        
        
        // Do any additional setup after loading the view, typically from a nib.
        
        phoneNumber.setBottomBorder(backGroundColor: .white, borderColor: GREEN_THEME)
        let cpv = CountryPickerView(frame: CGRect(x: 0, y: 0, width: 120, height: 20))
        phoneNumber.leftView = cpv
        phoneNumber.leftViewMode = .always
        
        

        
       
        
    }

    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }

    @IBAction func loginAction(_ sender: Any) {
        print("\(phoneNumber.text)")
     
    }
    
}

`

**Comment by kizitonwose** [comment]
The library only handles country code information. You need to retrieve the phone number from your text field.
E.g: `print("\(countryCodeView.selectedCountry.phoneCode)\(phoneNumberField.text)")`
