### ISSUE TITLE
Is there any way where I can disable some countries?

### ISSUE THREAD

**Issue by hardikamal** [kizitonwose/CountryPickerView#23]
Hi @kizitonwose 
Thanks for the awesome library.
Is there any way where I can disable some countries?

**Comment by kizitonwose** [comment]
You can't disable some countries but you can choose to show only some countries by returning those countries in the `preferredCountries(in countryPickerView: CountryPickerView) -> [Country]` method of `CountryPickerViewDataSource` and then set the framework to show only those preferred countries by returning `true` in the `showOnlyPreferredSection(in countryPickerView: CountryPickerView) -> Bool` method of `CountryPickerViewDataSource`

**Comment by TeamChang** [comment]
func showOnlyPreferredSection(in countryPickerView: CountryPickerView) -> Bool {

        return true
    }

    func preferredCountries(in countryPickerView: CountryPickerView) -> [Country] {

        return ["US","GB","NG","KE","UG","GH","AT","DE","BE","FR","IE","IT","NL","PL","PT","ES","SE"].compactMap { countryPickerView.getCountryByCode($0) }
    }
    
    func sectionTitleForPreferredCountries(in countryPickerView: CountryPickerView) -> String? {
        
        return "Supported Countries"
    }
