### ISSUE TITLE
Does it support Arabic?

### ISSUE THREAD

**Issue by mob-rockstar** [kizitonwose/CountryPickerView#25]
Even if I change the locale into Arabic, this picker view is showing only English Country name.

**Comment by serjooo** [comment]
If you check the way the country picker gets its data. It has a JSON data file in the resources folder and all the countries are in English.

If you want to support Arabic you would need to make JSON data file for arabic and accordingly load the right file during runtime according to Locale.

**Comment by kizitonwose** [comment]
@serjooo Thanks for helping out.
