### ISSUE TITLE
How to change padding in UIView?

### ISSUE THREAD

**Issue by wellbranding** [kizitonwose/CountryPickerView#26]
How can I change margin of country label and flag inside UIView which is used as CountryPickerView? Right now flag does not have any margin to the parent view..

**Comment by kizitonwose** [comment]
`CountryPickerView` class has a `flagSpacingInView` property. I believe that's what you need.

**Comment by wellbranding** [comment]
How does it work? which float should I provide? if I use CGFloat(bitPattern: 10) it does affect. If I use other float I get a crash. can you be more specific?
 Also how can I center text of country in the view?

**Comment by kizitonwose** [comment]
It takes a regular CGFloat, e.g `1.0`, `2.5` etc
If you have an instance of `CountryPickerView` named `cpv`, you can change the value like this: `cpv.flagSpacingInView = 2.5`

Also, you cannot center the Country name on the list.

**Comment by wellbranding** [comment]
It worked. However how can I move flag from the left edge itself?

**Comment by kizitonwose** [comment]
You need to increase the `constant` value of the view's leading constraint.

**Comment by wellbranding** [comment]
can you provide an example? :)

**Comment by kizitonwose** [comment]
Using the same `cpv` from the example above, that would be: 
`cpv.leadingAnchor.constraint(equalTo: view.safeAreaLayoutGuide.leadingAnchor, constant: 20).isActive = true`
You can change the value of the `constant` parameter to fit your use case.

**Comment by kizitonwose** [comment]
I'll be closing this issue now since the problem is solved.
