### ISSUE TITLE
crash in search and select code 

### ISSUE THREAD

**Issue by omarhassansadek** [kizitonwose/CountryPickerView#27]
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Application tried to present modal view controller on itself. Presenting controller is <UISearchController: 0x7ffccd57b340>.'
//my code
var CountryPickerCode = CountryPickerView()
  override func viewDidLoad() {
        super.viewDidLoad()
CountryPickerCode = CountryPickerView(frame: CGRect(x: 0, y: 0, width: txtCode.frame.size.width-10, height: txtCode.frame.size.height-10))
        CountryPickerCode.delegate=self
        txtCode.leftView = CountryPickerCode
        txtCode.leftViewMode = .always
}
func countryPickerView(_ countryPickerView: CountryPickerView, didSelectCountry country: Country) {
        
        self.CountryCode=country.phoneCode
        txtCode.leftView=CountryPickerCode
        txtCode.leftViewMode = .always

    }

**Comment by kizitonwose** [comment]
I cannot replicate this issue. Kindly provide a sample project and reopen the issue if you're still experiencing the crash.
