### ISSUE TITLE
when will bitcode be enabled

### ISSUE THREAD

**Issue by wellbranding** [kizitonwose/CountryPickerView#30]
Hello, when will bitcode be enabled for countryPickerview? This makes our project enable to archive. Can you fix it soon?
`ld: bitcode bundle could not be generated because '/...-hkkklqumysmrlnaulunyqgxvswbc/Build/Products/Release-iphoneos/CountryPickerView/CountryPickerView.framework/CountryPickerView' was built without full bitcode. All frameworks and dylibs for bitcode must be generated from Xcode Archive or Install build file '/..-hkkklqumysmrlnaulunyqgxvswbc/Build/Products/Release-iphoneos/CountryPickerView/CountryPickerView.framework/CountryPickerView' hkkklqumysmrlnaulunyqgxvswbc/Build/Products/Release-iphoneos/CountryPickerView/CountryPickerView.framework/CountryPickerView' for architecture arm64`

**Comment by kizitonwose** [comment]
Bitcode is enabled in the framework. You can pull the code and confirm this.
