### ISSUE TITLE
Flag for Iraq

### ISSUE THREAD

**Issue by arunvkdas** [kizitonwose/CountryPickerView#32]
The flag of Iraq is still the old one. Please update the image of the Iraq flag.

**Comment by arunvkdas** [comment]
This is serious as our app is being fined for using wrong flag. Else i need to work on changing the library used. Please update this flag 

[data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAOMAAACXCAMAAADQ4xypAAAAk1BMVEUAAADOESb////NCiIODg7AwMDOFSjwwsUAej221sUcfEAAcisAdTPl8euu0L0Af0EzhE/W6N/M4dYvgEd8tJQ6h1ZSmm/Y5Nzf6eJunXf2+vgAahgAbSBll27v9PHD08WNu6BGkmSbwamQtpxoo38chU2hwKtinnajy7XC3M6yy7pxp4ZJiVeDsJFUlGohdzYAZQAfXrrRAAADT0lEQVR4nO3ZC3OaQBSGYUpvC3uWcImUbAgFo1ViNf3/v67LxYkG6iTtauXM90xGxewY3llYxTgf+HP+9w5cABp5QCMPaOQBjTygkQc08oBGHtDIAxp5QCMPaOQBjTygkQc08oBGHtDIAxp5QCMPaOQBjTygkQc08oBGHpyP/Dlf+HO+8ue4/KGRBzTygEYe0MjDFTUqdaYXvqLGdXmmF75IY1EXB1t1oEdH1eXL86osRsf8lYs0lkvvYCugTTxWUGSmrcmsI1dR6lk7dC/ROCcZRi+bAclkPTKsMFUrE1ZXsatupH87Pt3vd4HGksgvDyYlIKLXc6S9wFvR8jnVrpckTSOJwNYOnL1RLSQdHapNYzocVqZzk2oePciwbZx9s7UL525sEsOjxPHGXlG4DzSxRpUShfXxcyca1SaeXGO2k4PEE43x7nlyjWo3nMVTjXcymVpjlEqaDRL/1GjWmzuaWmO0ks0+v9DdO8Z4Y/FYTK9RVZL8gxVV19tdO6mjjdnmWXWNd9NpVGYWhXe4nRAlzcfQscZsJZMpNWbNIWmWG3H01p9KQSTkVo821kuaUKOOk+/mdiuFP9dFSxlRLujWPCmykUat42oKjUXUfYQul7/6xuVdZ7WrDBLk6Vz4w0Ydl9vNFOYxXm37xjxvG++lzO9bectsetqsQsNGLzS/E+LqGxehTLtrwrhtdIPN7YByD+ZR76+czOIkFuVSJO17R3TUaOcS0lJjaU63NIhVpgIpt4HhDQVr2TdWRZ3u3znjpaByHQr/cV6Rv/0x6xvDWC3sfPthqbFYmvNN0o0Q5ofkn4iu0dwJub889HzRrLhCyJy6m7bRjLnJN1Yuk22dj2tzRr1F32hi9vsfDMb0jUYVnf6rb2OrUcl3NgrRn2ynGunJxr7Zaiwqemfj/mBdvx7Sn4/tmK2Ng9VWo96Y9eQtmsb2gewXFC957adp7AZTamNltdiYr0fW0gHtqv5Rv7AW0YB2dT+mvqZ5zHxZNffRub7Q/weWGlWa+82FUzxb2fpW1B4rjXru591FRhwubLygXVYas3n51B+j1zeLV/V/q7NBIw9o5AGNPKCRB+czf84n/hwAAAAAAAAAAAAAAAAAAAAAAAAAAACw6jcrStykotFC0QAAAABJRU5ErkJggg==](url)

**Comment by kizitonwose** [comment]
This has been fixed in version [2.2.3](https://github.com/kizitonwose/CountryPickerView/releases/tag/2.2.3)
