### ISSUE TITLE
Carthage doesn't work

### ISSUE THREAD

**Issue by ikbalyasar** [kizitonwose/CountryPickerView#36]
error;
019-02-15 15:50:52.666326+0300 "[15045:5380788] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Could not load NIB in bundle: 'NSBundle </var/containers/Bundle/Application/8952FEB6-1515-4844-B9AF-18975BCBF6C3/xxx.app/Frameworks/CountryPickerView.framework/CountryPickerView.bundle> (not yet loaded)' with name 'CountryPickerView''
@kizitonwose 
Can you try carthage?

**Comment by kizitonwose** [comment]
This is now fixed in version [2.2.2](https://github.com/kizitonwose/CountryPickerView/releases/tag/2.2.2). 
Kindly update the framework and thanks for reporting the issue.
