### ISSUE TITLE
Why I get check icon next to country

### ISSUE THREAD

**Issue by wellbranding** [kizitonwose/CountryPickerView#38]
I press customCountry button which launches country list. For some strange issue I can see one country as already being checked... In some devices this country is in the **middle** of the list, and on some it is the first country.

 Also if I remove countries from list or add some, it also affects country List and **makes a single country checked**. I would like to know why some countries **become selected even without** pressing them? It is definitively a bug which really creates problems for our use case... I would like to contribute for fixing this version.

**Comment by kizitonwose** [comment]
The library sets a default country which is derived from the current region code.

**Comment by wellbranding** [comment]
Can I change that? Because it does not make sense.. Also If I **removed that** country, which was derived from current region code, from countryPicker countries array, then some **random country** will be checked.. It is strange behavior. Why it is not **optional**?

**Comment by kizitonwose** [comment]
There's a default country because the library has to always show a country on the view when added as a subview. You may not find this very useful if you use the library as a standalone picker.

**Comment by wellbranding** [comment]
Oh ok... I will switch then for a different picker.. It is strange however that such functionality is not optional. This issue will be definitely addressed by other developers soon. It does not make sense, that current **country should be checked**. It can be the top in the list, but definitely not checked, because it confuses users.

**Comment by kizitonwose** [comment]
Since you'll be using a different picker, I consider this issue resolved and will be closing it.

**Comment by wellbranding** [comment]
I would like to contribute and fix this strange behavior, but it seems you won't approve such changes. Am I clear?

**Comment by kizitonwose** [comment]
I am very happy to review a PR with the fix. 
How do you intend to approach the issue?

**Comment by wellbranding** [comment]
I would create an optional method similar to yours, which would apply **tick icon** or not initially :) 

Overall I like your library and don't hesitate to use it in our production code as a shared library, which really improves this library popularity, but this **initial tick icon** does create problems for us

**Comment by kizitonwose** [comment]
I don't understand what you mean by creating an optional method, could you kindly explain further?

**Comment by wellbranding** [comment]
:) I refered to a boolean(checkMarkEnabled) which would be set as either true or false, depending on the client needs. If checkMarkEnabled is set to false, then in the beggining no country is selected. Default is true, so it will not change functionality of the framework. 

However, if someone would need to remove checkMark, then they could do that :) It is easy to do, I am just really busy with jobs and stuff... :(

**Comment by kizitonwose** [comment]
Note: This feature is now available in version [3.0.2](https://github.com/kizitonwose/CountryPickerView/releases/tag/3.0.2)
