### ISSUE TITLE
Search results don't show if enter lowercase text

### ISSUE THREAD

**Issue by honcharenko13** [kizitonwose/CountryPickerView#42]
To fix that you need to change line 232 in CountryPickerViewController.swift to 
`} else if let array = countries[String(text.capitalized[text.startIndex])] {`

![simulator screen shot - iphone xs - 2019-02-25 at 21 26 42](https://user-images.githubusercontent.com/19774907/53363089-52218a80-3944-11e9-9c99-5ed807fe134e.png)
![simulator screen shot - iphone xs - 2019-02-25 at 21 26 48](https://user-images.githubusercontent.com/19774907/53363090-52ba2100-3944-11e9-9e44-6bf61f1cbfd9.png)

**Comment by kizitonwose** [comment]
Thanks for reporting the issue. It's now fixed in version [2.2.4](https://github.com/kizitonwose/CountryPickerView/releases/tag/2.2.4)

**Comment by honcharenko13** [comment]
cool, thanks!
