### ISSUE TITLE
How to get only country flag in "didSelectCountry" CountryPickerViewDelegate?

### ISSUE THREAD

**Issue by bhanuteja501** [kizitonwose/CountryPickerView#45]
Can we able to get only Country flag through **CountryPickerViewDelegate** ?

**Comment by kizitonwose** [comment]
You can get the flag from the `country` property.

```swift
func countryPickerView(_ countryPickerView: CountryPickerView, didSelectCountry country: Country) {
	let flag = country.flag
}
```

**Comment by bhanuteja501** [comment]
Perfect. Thanks @kizitonwose

**Comment by bhanuteja501** [comment]
Hi Kizitonwose/Countrypickerview,

I am using *Countrypickerview* in my project's. I want to show the
preferred country's and need to hide the remaining countries.

How can I achieve this?
Please find the attached file to this email. i.e., The code which I tried

-- 
Regards,

*Bhanuteja*
iOS Developer

*Nextbrain Technologies Pvt Ltd*,
#44, 2nd floor, 1st cross, 2nd main, Prasanth extension, Whitefield,
Bangalore - 560066.
Mobile: +91 7022863334 | Skype:live:annam.bhanuteja  |
www.nextbrainitech.com

DISCLAIMER: The information contained in this message (including any
attachments) is confidential and may be privileged. If you have received it
by mistake please notify the sender by return e-mail and permanently delete
this message and any attachments from your system. Any dissemination, use,
review, distribution, printing or copying of this message in whole or in
part is strictly prohibited. Please note that e-mails are susceptible to
change. Nextbrain Technologies Pvt Ltd (including its group companies)
shall not be liable for the improper or incomplete transmission of the
information contained in this email.

**Comment by kizitonwose** [comment]
`CountryPickerViewDataSource` has a method `showOnlyPreferredSection()`which controls the visibility of other countries on the list, just return `true` :
```swift
func showOnlyPreferredSection(in countryPickerView: CountryPickerView) -> Bool {
	return true
}
```

**Comment by bhanuteja501** [comment]
Tried that.

But didn't work.
I kept breakpoint in line number 45.

The compiler not getting inside *data source delegates*. Even I declared
*cpvInternal**.dataSource = **self* in line number 14

Please find the attached file for your reference

-- 
Regards,

*Bhanuteja*
iOS Developer

*Nextbrain Technologies Pvt Ltd*,
#44, 2nd floor, 1st cross, 2nd main, Prasanth extension, Whitefield,
Bangalore - 560066.
Mobile: +91 7022863334 | Skype:live:annam.bhanuteja  |
www.nextbrainitech.com

DISCLAIMER: The information contained in this message (including any
attachments) is confidential and may be privileged. If you have received it
by mistake please notify the sender by return e-mail and permanently delete
this message and any attachments from your system. Any dissemination, use,
review, distribution, printing or copying of this message in whole or in
part is strictly prohibited. Please note that e-mails are susceptible to
change. Nextbrain Technologies Pvt Ltd (including its group companies)
shall not be liable for the improper or incomplete transmission of the
information contained in this email.
