### ISSUE TITLE
Can't dismiss the CountryPickerViewController if the navigation bar is hidden

### ISSUE THREAD

**Issue by kdovbush** [kizitonwose/CountryPickerView#46]
**Steps to reproduce**
1. UIViewController embedded in the navigation controller with a hidden navigation bar
2. Text field has the CountryPickerView as a left view
3. User taps on the country code view.

**Actual behavior**
The CountryPickerViewController is pushed (because of the navigation controller), but there is no navigation bar with back button (see attached screenshot).

**Expected behavior**
The CountryPickerViewController has navigation bar with back or close button.

**Additional context**
Currently I can't find an easy way to **present** a picker controller if UINavigationController is a top view controller. This can be done by calling `showCountryList` method, but this method is called automatically if you tap on the text field left view.
It would be better to have an optional `parentViewController` property in the CountryPickerView class, that will allow you to specify which controller should present the CountryPickerViewController. If the property is nil, execute the current solution.

**Screenshots**
![Simulator Screen Shot - iPhone X - 2019-03-18 at 19 26 00](https://user-images.githubusercontent.com/17612136/54554276-63464000-49b4-11e9-8537-ab5d740b8f4e.png)

**Comment by kizitonwose** [comment]
I like the idea of adding an optional `parentViewController` property in the CountryPickerView class. 

However, for your use case, have you considered this approach:

In the `didShow` delegate method which is called after the CountryPickerViewController is pushed:
```swift
func countryPickerView(_ countryPickerView: CountryPickerView, didShow viewController: CountryPickerViewController)
```
you show the navigation bar, hence revealing the `back` button.

---

Then in the `didSelectCountry` delegate method which is called after the user selects a country:

```swift
func countryPickerView(_ countryPickerView: CountryPickerView, didSelectCountry country: Country)
```
you hide the navigation bar.

**Comment by kdovbush** [comment]
Thanks for the answer!

This issue was found during the tests.

In my use case I needed to **present** CountryPickerView controller above the current view controller embedded in the navigation controller. I resolved this by adding `presentingViewController` to the CountryPickerView class (as described in the first comment). But it would be better to have this feature in the main repo.

**Comment by kizitonwose** [comment]
The idea of setting the view controller is nice, I'll add it in the next release.
You can also open a PR with your current implementation.
