### ISSUE TITLE
 does not conform to protocol

### ISSUE THREAD

**Issue by antonkashpor** [kizitonwose/CountryPickerView#5]
Hi, I'm using Xcode 9.2 and Swift 4
When I'm trying to implement delegate method didSelectCountry, I get the error:
> Type 'MBRegisterTableViewController' does not conform to protocol 'CountryPickerViewDelegate'

but I already have 

`func countryPickerView(_ countryPickerView: CountryPickerView, didSelectCountry country: Country) {}`

**Comment by kizitonwose** [comment]
I think you're missing an underscore(`_`) 

The delegate method should be:
```swift
func countryPickerView(_ countryPickerView: CountryPickerView, didSelectCountry country: Country) { 
	
}
```

Note the underscore `_` which denotes a missing label for the first argument. This is missing in the code you provided.

**Comment by antonkashpor** [comment]
@kizitonwose Sorry, I have updated my answer. I have `_`-symbol. But it didn't resolve the issue.

**Comment by kizitonwose** [comment]
Well, I don't see any other reason why the protocol conformance wouldn't work. Can you provide a sample project where this issue can be reproduced?

**Comment by antonkashpor** [comment]
@kizitonwose sure, I've asked the question with gist

**Comment by kizitonwose** [comment]
@antonkashpor A gist isn't very helpful in this case. What you should do is: 
Create a new project with only `CountryPickerView` as the dependency. Implement `CountryPickerViewDelegate` in your ViewController and see if you still get the error. 
If that's the case, create a repo on GitHub and push the project there so I can take a look at it.

**Comment by sonnetm** [comment]
Im too having the same problem! Please help!

**Comment by mkhoshpour** [comment]
@antonkashpor @sonnetm 
please check if you have `Country` class defined in your target. you should change it's name

**Comment by kizitonwose** [comment]
I can confirm that this happens if you have a `Country` struct or class in your project. Since version 2.2.1, the library comes with a typealias `CPVCountry` which can be used in this case.

If you choose to use the `CPVCountry` typealias, your method signature will be: 
```
func countryPickerView(_ countryPickerView: CountryPickerView, didSelectCountry country: CPVCountry)
```

**Comment by tejasna** [comment]
Hi @kizitonwose, first of all great work! Really like the library. 

I was wondering if the typealias feature would be available for 1.x.x version some time, since my project is currently written in swift 3.

**Comment by kizitonwose** [comment]
@tejasna You can fork the project and add the typealias to the `swift3` branch for your use case. No further development will be happening in that branch.
