### ISSUE TITLE
Unable to mange tableview section height 

### ISSUE THREAD

**Issue by MuseerAnsari** [kizitonwose/CountryPickerView#54]
I want to reduce table view header height 
![Simulator Screen Shot - iPhone Xʀ - 2019-04-09 at 13 27 47](https://user-images.githubusercontent.com/17614820/55793446-95d2ec80-5acb-11e9-9c10-f2a9437c3cf5.png)

**Comment by kizitonwose** [comment]
Looks like this feature has not gained enough requests to be added to the library. The default works for most people, I guess. If you still want this, please fork the library and make adjustments which I think shouldn't be more than two lines of code or so. Will be closing this for now.
