### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by chimzycash** [kizitonwose/CountryPickerView#61]
Hello...
Came across your very nice project and as logo designer who loves to contribute to open source projects, I want to help contribute by creating a unique logo for your project which will give it its own identity.
Working on some cool logo design ideas currently... I will post the idea concepts here once i complete it, so you can give me your feedback to make any changes or tweak to suit your needs.

**Comment by kizitonwose** [comment]
Cool. Can't wait to see what you come up with.

**Comment by chimzycash** [comment]
I appreciate your response... Would share the design concept here once I finish it up, so you can give your feedback.

**Comment by chimzycash** [comment]
Hi @kizitonwose 
Here is the logo idea concept... You can give your feedback and also the logo color of your choice.

![LOGO DESIGN_COUNTRY PICKER VIEW_BACKGROUND_1](https://user-images.githubusercontent.com/37814297/58372783-ae338500-7f1a-11e9-834b-fba6fafdbe57.jpg)
![LOGO DESIGN_COUNTRY PICKER VIEW_BACKGROUND_2](https://user-images.githubusercontent.com/37814297/58372784-ae338500-7f1a-11e9-8056-44e54d96b384.jpg)
![LOGO DESIGN_COUNTRY PICKER VIEW_BACKGROUND_3](https://user-images.githubusercontent.com/37814297/58372786-aecc1b80-7f1a-11e9-80d8-92d86b97ff29.jpg)
![LOGO DESIGN_COUNTRY PICKER VIEW_BACKGROUND_4](https://user-images.githubusercontent.com/37814297/58372787-af64b200-7f1a-11e9-8e24-607e71f03637.jpg)
![LOGO DESIGN_COUNTRY PICKER VIEW_BACKGROUND_5](https://user-images.githubusercontent.com/37814297/58372788-affd4880-7f1a-11e9-840e-f501cbac31b1.jpg)
![LOGO DESIGN_COUNTRY PICKER VIEW_idea concept_NEW](https://user-images.githubusercontent.com/37814297/58372831-72e58600-7f1b-11e9-91cb-a8955b26a403.jpg)

**Comment by kizitonwose** [comment]
These all look good. However, I think a globe with some map outlines would more accurately represent countries?

**Comment by chimzycash** [comment]
Appreciate your feedback response

The location icon inside the globe sphere was used to fortify the country idea concept... Adding outlines inside the globe shape could potentially make the design overly complex since there's a negative space location icon... which isn't effective in small sizes

**Comment by chimzycash** [comment]
Here is an updated version @kizitonwose  ... removed the location icon

![LOGO DESIGN_COUNTRY PICKER VIEW_BACKGROUND_1](https://user-images.githubusercontent.com/37814297/58766343-537ed680-8575-11e9-8f4c-460a555e8901.jpg)
![LOGO DESIGN_COUNTRY PICKER VIEW_BACKGROUND_2](https://user-images.githubusercontent.com/37814297/58766344-55489a00-8575-11e9-8ff3-4db6f65c68b4.jpg)
![LOGO DESIGN_COUNTRY PICKER VIEW_BACKGROUND_3](https://user-images.githubusercontent.com/37814297/58766345-5679c700-8575-11e9-89a6-17db23d9428b.jpg)
![LOGO DESIGN_COUNTRY PICKER VIEW_BACKGROUND_4](https://user-images.githubusercontent.com/37814297/58766346-57125d80-8575-11e9-9902-fa5ab3318ec9.jpg)
![LOGO DESIGN_COUNTRY PICKER VIEW_BACKGROUND_5](https://user-images.githubusercontent.com/37814297/58766347-57aaf400-8575-11e9-9e9c-06e6be2afda8.jpg)
![LOGO DESIGN_COUNTRY PICKER VIEW_idea concept_NEW2](https://user-images.githubusercontent.com/37814297/58766348-58438a80-8575-11e9-872f-93a2086fd833.jpg)

**Comment by kizitonwose** [comment]
Looks great. I have to mention that the library's name `CountryPickerView` is one word.

**Comment by chimzycash** [comment]
Ok.. you didnt mention that on your previous response so as to make the adjustment in one go

**Comment by chimzycash** [comment]
Which of the options do you prefer?
you can suggest your preferred color

**Comment by kizitonwose** [comment]
> Which of the options do you prefer?

The second one from the top.

**Comment by chimzycash** [comment]
Any preferred color?

**Comment by kizitonwose** [comment]
The current color works for me.

**Comment by chimzycash** [comment]
ok great... would make the adjustment on the text

**Comment by chimzycash** [comment]
Fitting the text into a single string word makes it a too long for a logo...
The broken version works really well for a logo... But doesn't affect the actual library's name CountryPickerView

Think of the HP logo... but the actual company name is Hewlett-Packard

![LOGO DESIGN_COUNTRY PICKER VIEW_BACKGROUND_1b](https://user-images.githubusercontent.com/37814297/58766853-a78cb980-857b-11e9-9ff8-4844121bd8e0.jpg)

**Comment by chimzycash** [comment]
Hello @kizitonwose 
Will appreciate your opinion,..

**Comment by kizitonwose** [comment]
Sorry for the delayed reply. The second one from top actually has the text below the icon not on the side.

**Comment by chimzycash** [comment]
@kizitonwose  You mean this?

![LOGO DESIGN_COUNTRY PICKER VIEW_BACKGROUND_1c](https://user-images.githubusercontent.com/37814297/58836261-39fe8d00-8650-11e9-99e5-d2eeee5b0534.jpg)

**Comment by kizitonwose** [comment]
Yep, that's the one.

**Comment by chimzycash** [comment]
Ok... Glad you liked the design...
Would prepare the png files including vector files for your use

**Comment by chimzycash** [comment]
Hi @kizitonwose ... Got the files ready and created a Pull Request that includes the logo files and updated the ReadMe file with the preferred logo.

**Comment by kizitonwose** [comment]
Thank you very much for the effort. I'll review and merge the PR soon.

**Comment by kizitonwose** [comment]
Closing this issue as the PR is closed.
