### ISSUE TITLE
Unable to present countryList from NavigationController

### ISSUE THREAD

**Issue by ms-tii** [kizitonwose/CountryPickerView#69]
In my app every viewController is present modally, But my countryList view controller is pushed from left on Login screen, I don't know why ? I had also tried passing nil to hostViewController in viewWillAppear and vice versa, but doesn't work. 
In my other two classes Registration and Update profile countryList is present modally perfectly.
Please see the attached image of my storyboard.

![Screenshot 2019-05-22 at 2 54 26 PM](https://user-images.githubusercontent.com/43948059/59329805-6760d000-8d0d-11e9-86f6-65b533a68e8a.png)

**Comment by kizitonwose** [comment]
Don't pass `nil` to `hostViewController`, instead, pass a ViewController that is not an instance of UINavigationController.
For example, if your LoginViewCntroller is pushed onto a UINavigationController and you have the CountryPickerView in your LoginViewCntroller, pass `self` to `hostViewController`.

**Comment by ms-tii** [comment]
Thank you very much friend
