### ISSUE TITLE
Label in uitextfield left view not aligned with the text

### ISSUE THREAD

**Issue by NrmeenTomoum** [kizitonwose/CountryPickerView#71]
<img width="414" alt="Screen Shot 2019-07-11 at 1 26 13 PM" src="https://user-images.githubusercontent.com/19241793/61039461-d77f7600-a3df-11e9-9748-8d7f99cb12f2.png">

 it is not in the same line with textField @kizitonwose

**Comment by kizitonwose** [comment]
Closing this as the associated PR is closed.
