### ISSUE TITLE
Add country specific masks for phone numbers.

### ISSUE THREAD

**Issue by dosymbaev** [kizitonwose/CountryPickerView#81]
Could you please add text field masking with each country's phone number pattern.

**Comment by kizitonwose** [comment]
I don't follow. Could you kindly explain further?

**Comment by dosymbaev** [comment]
+1 (800) 262-0413 USA
+355 4 454 1815 ALBANIA

Every country has its phone number mask, and the textfield should be masked to the selected country's mask.

**Comment by kizitonwose** [comment]
Unfortunately, this is out of the scope of the library.
