### ISSUE TITLE
South Korea data is wrong.

### ISSUE THREAD

**Issue by yeansang** [kizitonwose/CountryPickerView#84]
In CountryCodes.json, South korea data is now like this.
{
"name": "Korea, Republic of South Korea",
"dial_code": "+82",
"code": "KR"
}
But, South Korea's official name is "Republic of Korea", or "Korea, Republic of Korea".

**Comment by kizitonwose** [comment]
I think we can have it as just "South Korea". I'll fix later. Do open a PR if you can.
