### ISSUE TITLE
iOS13 freeze UITextField when using CountryPickerView

### ISSUE THREAD

**Issue by cyjFS** [kizitonwose/CountryPickerView#85]
Update ios13, tap the UITextField with no responese. When i remove 'CountryPickerView', it's ok. I can't sure if that 'CountryPickerView' freeze UITextField in iOS13.

<img width="814" alt="屏幕快照 2019-10-15 下午1 55 47" src="https://user-images.githubusercontent.com/5468020/66804090-1fb8b200-ef54-11e9-91da-145d75d67b65.png">

**Comment by cyjFS** [comment]
> Update ios13, tap the UITextField with no responese. When i remove 'CountryPickerView', it's ok. I can't sure if that 'CountryPickerView' freeze UITextField in iOS13.
> 
> <img alt="屏幕快照 2019-10-15 下午1 55 47" width="814" src="https://user-images.githubusercontent.com/5468020/66804090-1fb8b200-ef54-11e9-91da-145d75d67b65.png">

Using iOS13.1 simulator will find the problem.

**Comment by neokree** [comment]
@cyjFS I verified with a real device that this is not an issue of the CountryPicker, but the simulator itself. I think it can be related to the new swipe function. If you want to use it with the simulator for now activate the "Hardware  -> Keyboard -> Connect Hardware Keyboard" and restart the simulator. The app will not freeze anymore

**Comment by cyjFS** [comment]
> @cyjFS I verified with a real device that this is not an issue of the CountryPicker, but the simulator itself. I think it can be related to the new swipe function. If you want to use it with the simulator for now activate the "Hardware -> Keyboard -> Connect Hardware Keyboard" and restart the simulator. The app will not freeze anymore

Thanks for your reply, we have resolved with other ways.

**Comment by Piyush-Sharma-Pandit** [comment]
@cyjFS i have got same problem with the real Device. Can you please tell me the other ways to solve this.
i had to use country view inside the other view than add this other view as the left view of the textField because of the monsterous size of the flag.

**Comment by Piyush-Sharma-Pandit** [comment]
@neokree You can also help if you want

**Comment by kizitonwose** [comment]
I do not have this issue unfortunately and hope everyone has sorted it out somehow. 
@Piyush-Sharma-Pandit If you still need help, let me know.
