### ISSUE TITLE
The name of the Iran country is wrong

### ISSUE THREAD

**Issue by hojatdelfan** [kizitonwose/CountryPickerView#86]
Hello
Please change the name of Iran country from "Iran, Islamic Republic of Persian Gulf" to "Islamic Republic of Iran" in CountryCodes.json file.
Of course "Iran" itself can be used

**Comment by kizitonwose** [comment]
It would be nice to open a PR for this.

**Comment by kizitonwose** [comment]
Also, let's have it as just `Iran` for consistency.

**Comment by hojatdelfan** [comment]
Thanks for the suggestion
i created pull request for this problem
