### ISSUE TITLE
Stop Localization

### ISSUE THREAD

**Issue by Emy87aa** [kizitonwose/CountryPickerView#90]
My App is in both Arabic and English Languages (Using MOLH Pod). I want this Pod to stay English in both Languages. How to do that (Stop Localization in this Pod)?

**Comment by kizitonwose** [comment]
I guess I can add a flag for this in the next release.

**Comment by kizitonwose** [comment]
Please see the new `localeForCountryNameInList` function in `CountryPickerViewDataSource` in version [3.0.5](https://github.com/kizitonwose/CountryPickerView/releases/tag/3.0.5).
Return the preferred locale(in your case English) to show the names in your desired language.
