### ISSUE TITLE
Performance problem. Takes 1 or 2 seconds to load the first time.

### ISSUE THREAD

**Issue by Ricardo1980** [kizitonwose/CountryPickerView#91]
Hello,

The first time you tap the view, it takes 1 or 2 seconds to present the dialog.
After that, it goes fast.
Perhaps there is a problem reading the nib file, I don't know. But I am using an iPhone X.

Do you have the same problem?

Using Instruments with my iPhone X I see that for 1.7 seconds the app is blocked when I tap the view and the problem is related to the load of the resources (images).

Using the demo app, instead of 1.7 seconds, it is just 0.7 seconds. (It does not matter if I use debug or release mode)

Do you know why this is different? Any suggestion?

Thanks.

<img width="1552" alt="Screenshot 2019-11-26 at 13 59 45" src="https://user-images.githubusercontent.com/738681/69639847-37a44b00-1055-11ea-8def-d40817913899.png">
<img width="1552" alt="Screenshot 2019-11-26 at 13 58 15" src="https://user-images.githubusercontent.com/738681/69639848-37a44b00-1055-11ea-8c4d-47d95140fbb3.png">

**Comment by kizitonwose** [comment]
> Do you have the same problem?

Nope. I haven't observed this issue. Don't think this is an issue in the library.
