### ISSUE TITLE
Crashes when I give only selected countries

### ISSUE THREAD

**Issue by maheshm504** [kizitonwose/CountryPickerView#93]
Hi Dear Developer

You missed something

When I give countries(array) = US
This condition fails

    internal(set) public var selectedCountry: Country {
        get {
            return _selectedCountry
                ?? countries.first(where: { $0.code == Locale.current.regionCode })
                ?? countries.first(where: { $0.code == "NG" })!
        }
        set {
            _selectedCountry = newValue
            setup()
        }
    } 

and app crashes

this should be optional like this **?**

**Comment by kizitonwose** [comment]
Whoops! That's true. I will fix this. I guess I can return the first country in the `countries` collection instead of `NG` which might not be there.

**Comment by kizitonwose** [comment]
Actually, after investigating this, I think you should use the preferred countries feature instead and set the library to show only preferred countries. The `countries` array was supposed to be private, not sure how it became public.
