### ISSUE TITLE
Detect Country Code from provided Phone Number (if any)

### ISSUE THREAD

**Issue by JaceTan** [kizitonwose/CountryPickerView#97]
Problem: 
With build 3.0.5, the `countries` is now internal and this breaks an extension function I wrote for my project that needs to initialize an array of countries for manipulation.

Possible Solutions:
1. If there's a function in CountryPickerView that does what I need (i.e. detect the Country given a Phone Number that may or may not contain a country code), then I can use it. My current ext func returns me the Phone Code as a String if found, otherwise returns an empty String. If CPV has a func that does this, I don't mind if it returns an Optional Country, String, or Array.
2. If there's another way to get a read-only list of `countries`, I can make a copy for manipulation.
3. If the above 2 solutions don't work, maybe include the function I wrote (see below) in a new release?
4. I can just use v3.0.4, but I'm the kind of person that likes to keep everything up to date. (This is what I'm doing for now)
5. I could make a fork of 3.0.5 and add my function, but then my project would need to point to my fork, and I would have to constantly rebase, and I don't really wanna have to maintain yet another lib if I don't have to. 

More details:
In my project, I wrote an extension function to extract the Country Code (if any) from a provided phone number.
The intention was so that if a User pastes in a phone number into a text field, the CountryPicker can use this function to detect the country code. If a country code is found, my VC can change the flag and remove the country code from the pasted text.

E.g.
If a User pastes "+6512345678" into the TextBox, then the CountryPickerView will update the flag to 🇸🇬 and the TextBox would display "12345678".

But if a User pastes "12345678" into the TextBox, then the CountryPickerView will not update the flag and the TextBox would display "12345678".

This is the function itself with comments. I chose to return a String because I'd rather deal with empty Strings than have to unwrap Optionals and I didn't need the Country (just the CountryCode) in order to manipulate the pasted PhoneNumber String.
```
func extractCountryCodeFromPhoneNumber(_ phoneNumber: String) -> String {
    guard phoneNumber.count > 1 else { return "" }
    var possibleCodes = countries.map { $0.phoneCode }
    for i in 2...phoneNumber.count {
        let code = phoneNumber.prefix(i).string

        // Need to make sure both the current code and the possibleCodes start with each other to prevent false negatives.
        // E.g. if current code is "+12", this ensures that "+1" (US/Canada) is still included as a possible code
        // while also including "+1242" (Bahamas), "+1264" (Anguila) and "+1246" (Barbados).
        possibleCodes = possibleCodes.filter { $0.starts(with: code) || code.starts(with: $0) }

        // If there no more possible codes, return empty String since there's no point continuing the search.
        if possibleCodes.isEmpty { return "" }

        // If there's only 1 possibleCode and the phoneNumber starts with it, return it.
        // This prevents false positives where checking the code partially returns a single possibleCode but the rest of the phoneNumber doesn't match.
        // E.g. The phoneNumber is like "+878783..." and the current code is "+87", so the only possibleCode is "+872" (Pitcairn).
        // This check will ensure that the phoneNumber actually does starts with "+872".
        // Since this example does not start with the only possibleCode, it will not return it.
        if possibleCodes.count == 1 && phoneNumber.starts(with: possibleCodes[0]) { return possibleCodes[0] }
    }

    // If there are still many possibleCodes even after going through the whole phoneNumber, find the longest possibleCode and return it.
    // E.g. if the phoneNumber is like "+12429832...", this ensures that it returns "+1242" (Bahamas) rather than "+1" (US/Canada).
    return possibleCodes.reduce("") { $0.count > $1.count ? $0 : $1 }
}
```

**Comment by kizitonwose** [comment]
The `countries` property is now public again in `3.0.6`.

**Comment by JaceTan** [comment]
Thanks!
