### ISSUE TITLE
Netherlands Antilles

### ISSUE THREAD

**Issue by tejasna** [kizitonwose/CountryPickerView#99]
Hi there, 

Just an observation not sure if this is reproducible. I'm not able to see Netherlands Antilles in the list of countries, although I see it the CountryCodes.json.

I don't have the preferred countries list set as well. Any input will be of great help!

Thanks again for the hard work!

**Comment by kizitonwose** [comment]
Looks like the country [no longer exists](https://en.wikipedia.org/wiki/Netherlands_Antilles).
I have not checked to see if I can reproduce the actual issue though, so maybe deleting the country from CountryCodes.json would be the easy way out 🤷‍♂

**Comment by tejasna** [comment]
Ok thanks! that makes sense. 
Created a [pull request](https://github.com/kizitonwose/CountryPickerView/pull/100)

Closing the issue.
